1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

In [1]:
import numpy as np

arr = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
arr

array([[   6.,   -8.,   73., -110.],
       [  nan,   -8.,    0.,   94.]])

In [4]:
arr = np.nan_to_num(arr, nan=0)
arr

array([[   6.,   -8.,   73., -110.],
       [   0.,   -8.,    0.,   94.]])

In [7]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

2) Move axes of 3D array to new positions

In [16]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
moved = np.moveaxis(arr, 0, 2)
moved

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

3) Replace NaN values with average of columns

In [27]:
arr = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
arr

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [29]:
col_mean = np.nanmean(arr, axis=0)

for i in range(arr.shape[1]):
    arr[:, i] = np.nan_to_num(arr[:, i], nan=col_mean[i])

arr

array([[1. , 2. , 7.5],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

4) Replace negative value with zero in numpy array using replace

In [30]:
arr = np.array([[-1, 2, -3], [4, -5, 6]])
arr

array([[-1,  2, -3],
       [ 4, -5,  6]])

In [31]:
arr[arr < 0] = 0
arr

array([[0, 2, 0],
       [4, 0, 6]])