1) Combining a One-Dimensional and a Two-Dimensional NumPy Array

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2) Flatten a 2D Array into 1D

In [2]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


3) Reverse a NumPy Array

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[::-1])

[5 4 3 2 1]


4) Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy

In [4]:
arr = np.array([10, 20, 5, 40])

print(np.max(arr))
print(np.min(arr))
print(arr.shape)

40
5
(4,)


In [5]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)

print(arr[0,1])

[[1 2 3]
 [4 5 6]]
2


In [6]:
total = 0

for row in arr:
    for val in row:
        total += val

print(total)

21


In [7]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


5) Iterate 3D array using for loop and nditer

In [8]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

for block in arr:
    for row in block:
        for val in row:
            print(val, end=" ")

print()

for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 

6) Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays

In [9]:
arr1 = np.array([3, 4])
arr2 = np.array([1, 0])

avg = (arr1 + arr2) / 2
print("Average of NumPy arrays:\n", avg)

Average of NumPy arrays:
 [2. 2.]


In [11]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

# Sum of corresponding elements
arr = arr1.flatten() + arr2.flatten()

# Mean
mean = np.mean(arr)
print("Mean:", mean)

# Median
median = np.median(arr)
print("Median:", median)

Mean: 9.0
Median: 9.0
